### PR TITLE
Demo 1 preperaion : stages a and b

### PR DESCRIPTION
**Pull request by DanWaldman**
a - A working Vagrant environment that brings up the default django web server
b - A basic Django application that includes a static web page

### CODE REVIEW

**Comment by bregman-arie** [comment]
@DanWaldman before we merge this change, can you or someone from your team fix the CI?:

"Error: the command flake8 could not be found within PATH or Pipfile's [scripts]."

**Comment by ifireball** [comment]
I think this PR includes too much it it - among other things, it includes a mix of auto-generated and manually-written code - so its hard for a reviewer to know what is what

**Comment by DanWaldman** [comment]
> I think this PR includes too much in it - among other things, it includes a mix of auto-generated and manually-written code - so its hard for a reviewer to know what is what

**Comment by DanWaldman** [comment]
I'll rearrange the commits and PR again.

**Comment by DanWaldman** [comment]
Should I close the PR?

**Comment by ifireball** [comment]
you can update the PR with fewer stuff if you don't want to "waste" the PR number...

**Comment by ifireball** [comment]
if you do not intend for it to be merged - you sohuld close it

**Comment by DanWaldman** [comment]
okay, thanks

**Pull request closed without merging**
